### ISSUE TITLE
Problems installing

### ISSUE THREAD

**Issue by MagunRa** [alessandrojcm/commitlint-pre-commit-hook#28]
Whe commiting I get the following message: 
```
An unexpected error has occurred: CalledProcessError: command: ('C:\\Users\\Moritz\\.cache\\pre-commit\\repoeoat780j\\node_env-default\\Scripts\\npm.CMD', 'install', '--dev', '--prod', '--ignore-prepublish', '--no-progress', '--no-save')
return code: 1
expected return code: 0
stdout:
    
    added 195 packages, and audited 196 packages in 6s
    
    3 low severity vulnerabilities
    
    To address all issues, run:
      npm audit fix --force
    
    Run `npm audit` for details.
    
stderr:
    Das System kann den angegebenen Pfad nicht finden. (<< this means System coulnd't find the speciefied path)
    Das System kann den angegebenen Pfad nicht finden.
    npm WARN install Usage of the `--dev` option is deprecated. Use `--include=dev` instead.
    
```

This error occured today, before it worked fine.

**Comment by alessandrojcm** [comment]
Hey, sorry for the late reply.

Could you share your pre-commit config please? Also, would it be possible for you to try this on a Linux system?

**Comment by MagunRa** [comment]
Hi,
the config is:
```
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.4.0
    hooks:
      - id: fix-byte-order-marker
      - id: check-merge-conflict
      - id: end-of-file-fixer
      - id: mixed-line-ending
      - id: trailing-whitespace
      - id: check-yaml

  - repo: https://github.com/alessandrojcm/commitlint-pre-commit-hook
    rev: v4.1.0
    hooks:
      - id: commitlint
        stages: [ commit-msg ]
        additional_dependencies: [ '@commitlint/config-conventional' ]
```

I have tried it on other systems Linux as well as a fresh Windows. I couldn't reproduce the error.
Thus, the errors is probably on my side, but I cannot find out where it is.
