### ISSUE TITLE
RangeError: Found invalid rule names: subject-exclamation-mark

### ISSUE THREAD

**Issue by ocofaigh** [alessandrojcm/commitlint-pre-commit-hook#48]
Any idea why I get this error?

.pre-commit-config.yaml:
```
default_stages: [commit]
repos:
  - repo: https://github.com/alessandrojcm/commitlint-pre-commit-hook
    rev: v5.0.0
    hooks:
      - id: commitlint
        stages: [commit-msg]
        additional_dependencies: ['@commitlint/config-angular']
```

commitlint.config.js:
```
module.exports = {
    extends: [
        '@commitlint/config-angular'
    ]
}
```

Executed commands:
```
pre-commit install --hook-type commit-msg
git commit -m "fix: test"
```

Error:
```
commitlint...............................................................Failed
- hook id: commitlint
- exit code: 1

/Users/conall/.cache/pre-commit/repoh90wjh3h/node_env-system/lib/node_modules/commitlint-pre-commit-hook/node_modules/@commitlint/cli/lib/cli.js:112
        throw err;
        ^

RangeError: Found invalid rule names: subject-exclamation-mark. Supported rule names are: body-case, body-empty, body-full-stop, body-leading-blank, body-max-length, body-max-line-length, body-min-length, footer-empty, footer-leading-blank, footer-max-length, footer-max-line-length, footer-min-length, header-case, header-full-stop, header-max-length, header-min-length, references-empty, scope-case, scope-empty, scope-enum, scope-max-length, scope-min-length, signed-off-by, subject-case, subject-empty, subject-full-stop, subject-max-length, subject-min-length, type-case, type-empty, type-enum, type-max-length, type-min-length
    at Object.lint [as default] (/Users/conall/.cache/pre-commit/repoh90wjh3h/node_env-system/lib/node_modules/commitlint-pre-commit-hook/node_modules/@commitlint/lint/lib/lint.js:53:15)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async Promise.all (index 0)
    at async main (/Users/conall/.cache/pre-commit/repoh90wjh3h/node_env-system/lib/node_modules/commitlint-pre-commit-hook/node_modules/@commitlint/cli/lib/cli.js:196:21)
```

**Comment by Begi** [comment]
@ocofaigh 
try this:
```yml

- repo: https://github.com/alessandrojcm/commitlint-pre-commit-hook
    rev: v5.0.0
    hooks:
      - id: commitlint
        stages: [commit-msg]
        additional_dependencies: ['@commitlint/config-angular@12.1.4']
```

@alessandrojcm  maybe time to upgrade to version v15 ?

https://github.com/alessandrojcm/commitlint-pre-commit-hook/pull/56
https://github.com/alessandrojcm/commitlint-pre-commit-hook/pull/57
