### ISSUE TITLE
Configuring config location

### ISSUE THREAD

**Issue by cc-gb2** [alessandrojcm/commitlint-pre-commit-hook#66]
Hi,

I really like how this works, but I'm having an issue setting the location of the commitlint file. Ideally, I'd be able to set the commitlint config to `.commitlint.config.js` like this:
```
repos:
  - repo: https://github.com/alessandrojcm/commitlint-pre-commit-hook
    rev: v7.0.1
    hooks:
      - id: commitlint
        stages: [commit-msg]
        additional_dependencies: ["@commitlint/config-conventional"]
        args: ['--config','.commitlint.config.js']
```
which should work according to the commitlint arguments. However, I get the error `Unknown argument: .git/COMMIT_EDITMSG`. 

Is it possible to use `args` like shown above?
