### ISSUE TITLE
Use Other Filenames for commintlint Config

### ISSUE THREAD

**Issue by seanwu1105** [alessandrojcm/commitlint-pre-commit-hook#91]
According to the [README of commitlint](https://github.com/conventional-changelog/commitlint#config), by default, commitlint looks for the following filenames:

- `.commitlintrc`
- `.commitlintrc.json`
- `.commitlintrc.yaml`
- `.commitlintrc.yml`
- `.commitlintrc.js`
- `.commitlintrc.cjs`
- `.commitlintrc.ts`
- `commitlint.config.js`
- `commitlint.config.cjs`
- `commitlint.config.ts`

I try to create `.commitlintrc.json` for the configuration:

```json
{
  "extends": ["@commitlint/config-conventional"],
  "header-max-length": 50,
  "body-max-line-length": 80,
  "footer-max-length": 50
}
```

With `.pre-commit-config.yaml`:

```yaml
- repo: https://github.com/alessandrojcm/commitlint-pre-commit-hook
  rev: v9.1.0
  hooks:
    - id: commitlint
      stages: [commit-msg]
      additional_dependencies: ["@commitlint/config-conventional"]
```

And I got the following error message:

```
✖   Please add rules to your `commitlint.config.js`
    - Getting started guide: https://commitlint.js.org/#/?id=getting-started
    - Example config: https://github.com/conventional-changelog/commitlint/blob/master/%40commitlint/config-conventional/index.js [empty-rules]

✖   found 1 problems, 0 warnings
ⓘ   Get help: https://github.com/conventional-changelog/commitlint/#what-is-commitlint
```

Could we support other default filenames as the commitlint config?
